language: php

php:
  - 7.0

env:
  - NO_INTERACTION=1 TEST_TIMEOUT=120

sudo: false

before_script:
  - sh -c "./build-libsphinx.sh"
  - sh -c "phpize && ./configure && make"

script:
  - sh -c "make test | tee result.txt"
  - sh test-report.sh
